# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('icon.ico', '.'),
        ('config.py', '.'),
        ('logger.py', '.'),
        ('shot.py', '.'),
        ('window.py', '.'),
        ('excelexport.py', '.'),
        ('resource_path.py', '.'),
        ('dialogs.py', '.'),
        ('vm_manager.py', '.'),
        ('ui_manager.py', '.'),
        ('file_manager.py', '.'),
        ('vm_scanner.py', '.'),
        ('settings_dialog.py', '.'),
    ],
    hiddenimports=[
        'PyQt6.QtWidgets', 
        'PyQt6.QtCore', 
        'PyQt6.QtGui',
        'PIL',
        'PIL.ImageGrab',
        'PIL.Image',
        'openpyxl',
        'openpyxl.drawing.image',
        'keyboard',
        'win32gui',
        'socket',
        'threading',
        'json',
        'logging',
        'logging.handlers',
        'dataclasses',
        'typing'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Auto Screenshot Tool',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['icon.ico'],
)
